services:
  - type: web
    name: infinihumanizer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: from-dashboard
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        value: from-dashboard
