# Generated by Django 5.2.1 on 2025-11-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_whatsappverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_active_devices',
            field=models.IntegerField(default=0, help_text='Currently active device sessions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_device_switches',
            field=models.IntegerField(default=0, help_text='Number of different devices used today'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_device_reset',
            field=models.DateField(blank=True, help_text='Last date device counter was reset', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_concurrent_devices',
            field=models.IntegerField(default=1, help_text='Maximum devices that can be logged in simultaneously'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current plan expires', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('KE_DAILY', 'Kenya Daily'), ('KE_WEEKLY', 'Kenya Weekly'), ('KE_MONTHLY', 'Kenya Monthly'), ('KE_MULTI_DEVICE', 'Kenya Multi-Device')], default='FREE', max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Unique device identifier hash', max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
