# Generated by Django 5.2.1 on 2025-05-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_anonymousquota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousQuota',
        ),
    ]
